version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile

    volumes:
      - ./front:/app
      - /app/node_modules

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    logging:
      driver: none
    ports:
      - "80:80"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./back

    volumes:
      - /app/node_modules
      - ./back:/app
