version: '3'
services:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile

    volumes:
      - /app/node_modules
      - ./front:/app
    
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    logging:
      driver: none
    ports:
      - '80:80'

  api:
    build:
      dockerfile: Dockerfile
      context: ./back

    volumes:
      - /app/node_modules
      - ./back:/app
