version: '3'
services:
     
  nginx:
    restart: always

    image: jeffreyyang0/vintage_blackjack:nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'

  api:
    restart: always
    image: jeffreyyang0/vintage_blackjack:api
    build:
      dockerfile: Dockerfile
      context: ./back

    volumes:
      - /app/node_modules
      - ./back:/app
