version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    logging:
      driver: none

  api:
    build:
      dockerfile: Dockerfile
      context: ./back

    volumes:
      - /app/node_modules
      - ./back:/app
